"""create_department

Revision ID: 8fa5f918b257
Revises: 
Create Date: 2023-08-13 22:04:33.335138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa5f918b257'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hired_employees_id', table_name='hired_employees')
    op.drop_table('hired_employees')
    op.drop_index('ix_jobs_id', table_name='jobs')
    op.drop_index('ix_jobs_job', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('jobs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('job', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='jobs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_jobs_job', 'jobs', ['job'], unique=False)
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    op.create_table('hired_employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='hired_employees_department_id_fkey'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='hired_employees_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hired_employees_pkey')
    )
    op.create_index('ix_hired_employees_id', 'hired_employees', ['id'], unique=False)
    # ### end Alembic commands ###
