version: '3.8'

services:
  postgresserver:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: pswd12345
    #   POSTGRES_DB: postgres

  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./file_storage:/file_storage
      - ./api:/api
    depends_on:
      - postgresserver
volumes:
  file_storage: